=== Ayush-CU/ayush-cu.github.io/CIA-1/EMS.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="Company">
		<xsd:complexType>
		
		<xsd:element name="Members">
			<xsd:complexType>
				<xsd:sequence>
					<xsd:element name="ID" type="xs:integer"/>
					<xsd:element name="Emp-name" type="xs:string"/>
					<xsd:element name="Emp-age" type="xs:integer"/>
					<xsd:element name="Emp-salary" type="xs:integer"/>>
						<xsd:simpleType>
    							<xsd:restriction base="xs:integer">
									<xsd:minInclusive value="50000"/>
      								<xsd:maxInclusive value="200000"/>
      							</xsd:restriction>
  						</xsd:simpleType>	
					</xsd:element>
					<xsd:element name="Emp-emailid" type="xs:string"/>
					<xsd:element name="Emp-Phonenum" type="xs:integer"/>
					<xsd:element name="Emp-designation" type="xs:integer"/>
					
				</xsd:sequence>	
			</xsd:complexType>
		</xsd:element>

	</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== Ayush-CU/ayush-cu.github.io/CIA-1/EMS.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="EMS.xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="EMS.xsd">
	
	<Members id="1">
		<ID>1</ID>
		<Emp-name>Abhishek</Emp-name>
		<Emp-age>38</Emp-age>
		<Emp-salary>100000</Emp-salary>
		<Emp-emailid>Abhishek@gmail.com</Emp-emailid>
		<Emp-Phonenum>1111111111</Emp-Phonenum>
		<Emp-designation>Tech-Advisor</Emp-designation>
	</Members>
	
	<Members id="2">
		<ID>2</ID>
		<Emp-name>Aditya</Emp-name>
		<Emp-age>45</Emp-age>
		<Emp-salary>130000</Emp-salary>
		<Emp-emailid>Aditya@gmail.com</Emp-emailid>
		<Emp-Phonenum>2222222222</Emp-Phonenum>
		<Emp-designation>Hardware Specialist</Emp-designation>
	</Members>
	
	<Members id="3">
		<ID>3</ID>
		<Emp-name>Manish</Emp-name>
		<Emp-age>47</Emp-age>
		<Emp-salary>145000</Emp-salary>
		<Emp-emailid>Manish@gmail.com</Emp-emailid>
		<Emp-Phonenum>3333333333</Emp-Phonenum>
		<Emp-designation>Sub-Manager</Emp-designation>
	</Members>
	
	<Members id="4">
		<ID>4</ID>
		<Emp-name>Ram</Emp-name>
		<Emp-age>62</Emp-age>
		<Emp-salary>175000</Emp-salary>
		<Emp-emailid>Ram@gmail.com</Emp-emailid>
		<Emp-Phonenum>4444444444</Emp-Phonenum>
		<Emp-designation>Sub-Manager</Emp-designation>
	</Members>
	
	<Members id="5">
		<ID>5</ID>
		<Emp-name>Shyam</Emp-name>
		<Emp-age>44</Emp-age>
		<Emp-salary>Female</Emp-salary>
		<Emp-emailid>Shyam@gmail.com</Emp-emailid>
		<Emp-Phonenum>5555555555</Emp-Phonenum>
		<Emp-designation>Sub-Manager</Emp-designation>
	</Members>

	
</Company>
